language: generic # not true
env:
  matrix:
    - PY_VER=2.7
    - PY_VER=3.4
    - PY_VER=3.5
    - PY_VER=3.6
matrix:
  include:
    # - os: osx
    - os: linux
      sudo: required
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - os: linux
      sudo: required
      services: docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker pull $DOCKER_IMAGE
    fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker run -e PY_VER="${PY_VER}" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/recipe/build_manylinux.sh
    fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker run -e PY_VER="${PY_VER}" -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/recipe/test_manylinux.sh
    fi

# before_install:
#   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
#       if [ "$PY_VER" = "2.7" ]; then
#         wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
#       else
#         wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#       fi
#     elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
#       if [ "$PY_VER" == "2.7" ]; then
#         wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
#       else
#         wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
#       fi
#     fi
#   - bash miniconda.sh -b -p $HOME/miniconda
#   - export PATH="$HOME/miniconda/bin:$PATH"
#   - hash -r
#   - conda config --set always_yes yes --set changeps1 no
#   - conda update -q --all
#   - conda install conda-build anaconda-client
#   - conda create -n test python=${PY_VER} pytest
# install:
#   - conda build recipe --no-test --python ${PY_VER} -m recipe/ci_build.yaml
#   - . activate test || exit 1
#   - conda install pydrobert-kaldi --use-local || exit 1
# script:
#   - pytest
# deploy:
#   - provider: script
#     script: . deactivate; . recipe/travis_deploy.sh || exit 1
#     skip_cleanup: true
#     on:
#       tags: true

